[INT-929] Added new PluginMethod of Exporter (getSelectedAutoExportParams)
ddbotgitbooksync/dronedeploy-apps-gitbook pull request #26
Opened 2019-05-30 12:20 UTC by agataHappy

**Ticket**
https://dronedeploy.atlassian.net/browse/INT-929

**Work done**
Added new plugin method of Exporter to docs with example of usage.

2019-05-30 12:35 UTC, mikolaj-leszczynski commented
@agataHappy can you attach screenshots which show the work you have done?

2019-05-30 12:38 UTC, mikolaj-leszczynski requested changes

2019-05-30 12:38 UTC, mikolaj-leszczynski commented on docs/exporter/example-exporter.getselectedautoexportparams.md
> +    <h1 class="title sans">Export.send example</h1>
Ooops, something wen wrong when copying :P

2019-05-30 12:38 UTC, mikolaj-leszczynski commented on docs/exporter/example-exporter.getselectedautoexportparams.md
> +    <button type="button" id="export" class="btn">Export</button>
and here

2019-05-30 14:15 UTC, agataHappy commented on docs/exporter/example-exporter.getselectedautoexportparams.md
> +    <h1 class="title sans">Export.send example</h1>
Done

2019-05-30 14:15 UTC, agataHappy commented on docs/exporter/example-exporter.getselectedautoexportparams.md
> +    <button type="button" id="export" class="btn">Export</button>
Done

2019-05-31 07:58 UTC, mikolaj-leszczynski approved these changes

2019-05-31 07:58 UTC, merged